//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormulaDetalle
    {
        public int IdFormulaDetalle { get; set; }
        public int IdFromula { get; set; }
        public int IdInsumo { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<bool> Borrado { get; set; }
        public Nullable<int> IdUsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual Formula Formula { get; set; }
        public virtual Insumo Insumo { get; set; }
    }
}
