//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemisionDetalle
    {
        public int IdRemisionDetalle { get; set; }
        public int IdRemision { get; set; }
        public int IdProducto { get; set; }
        public Nullable<bool> Borrado { get; set; }
        public Nullable<int> IdUsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Remision Remision { get; set; }
    }
}
