//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public int IdPersona { get; set; }
        public string Username { get; set; }
        public string Contrasena { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<byte> IntentosBloqueo { get; set; }
        public Nullable<bool> Bloqueado { get; set; }
        public int IdUsuarioCreo { get; set; }
        public System.DateTime FechaCreo { get; set; }
        public Nullable<int> IdUsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
